### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by xsacha** [supernotman/RetinaFace_Pytorch#1]
How much memory do you estimate this project needs?
I'm using a Titan V with 12GB and this goes out of memory with a batch size of 16 (default was 32), which seems quite small for WIDER face.

I had to use a batch size of 8, which used 10GB.

**Comment by supernotman** [comment]
For me , I am using batch size of 32 and 36GB memory need.
And i have not tried batch size of 8 or smaller.

**Comment by supernotman** [comment]
> How much memory do you estimate this project needs?
> I'm using a Titan V with 12GB and this goes out of memory with a batch size of 16 (default was 32), which seems quite small for WIDER face.
> 
> I had to use a batch size of 8, which used 10GB.

For me , I am using batch size of 32 and 36GB memory need.
And i have not tried batch size of 8 or smaller.

**Comment by xsacha** [comment]
Thanks
