### ISSUE TITLE
Have you tested on widerface val?

### ISSUE THREAD

**Issue by luyao777** [supernotman/RetinaFace_Pytorch#10]
I have the following result of image size (1200,1200):
Easy       Val AP: 0.721983363755764
Medium Val AP: 0.742308954563704
Hard      Val AP: 0.6196879642610857

Is there something wrong?

**Comment by supernotman** [comment]
> I have the following result of image size (1200,1200):
> Easy Val AP: 0.721983363755764
> Medium Val AP: 0.742308954563704
> Hard Val AP: 0.6196879642610857
> 
> Is there something wrong?

can i know how you test ? or you can attach your testing code here

**Comment by supernotman** [comment]
> I have the following result of image size (1200,1200):
> Easy Val AP: 0.721983363755764
> Medium Val AP: 0.742308954563704
> Hard Val AP: 0.6196879642610857
> 
> Is there something wrong?

And if you check the source code of mxnet Retinaface, you will find that boxes voting and image pyramid of size([500, 800, 1100, 1400, 1700]) (i am not sure) are used, that may promotes result of evaluation.
By the way i have not test like that in val yet.The eval result of recall and precision showed when training is just a average result with input 640*640 in val which just for reference .
But with input 1200*1200 get AP 0.72 in Easy Val i think there may be something wrong.

**Comment by supernotman** [comment]
> > I have the following result of image size (1200,1200):
> > Easy Val AP: 0.721983363755764
> > Medium Val AP: 0.742308954563704
> > Hard Val AP: 0.6196879642610857
> > Is there something wrong?
> 
> And if you check the source code of mxnet Retinaface, you will find that boxes voting and image pyramid of size([500, 800, 1100, 1400, 1700]) (i am not sure) are used when eval, that may promotes result of evaluation.
> By the way i have not test like that in val yet.The eval result of recall and precision showed when training is just a average result with input 640×640 in val which just for reference .
> But with input 1200×1200 get AP 0.72 in Easy Val i think there may be something wrong.

**Comment by luyao777** [comment]
Yeah, I just use this code to test images in widerface-val one by one and output result into txt file. And use official eval-tools to get scores.
