### ISSUE TITLE
输入的图片对于任意的大小是否都可以呢？

### ISSUE THREAD

**Issue by verigle** [supernotman/RetinaFace_Pytorch#15]
在detect.py 文件中，有padded image 这一环节，你是否考虑过对于大小不是640×640的图片，在padding和resize之后输入的模型中，得到的人脸框的位置和关键点的位置与原图之间会有偏移？这个偏移是否应该在显示的时候矫正一下呢？

**Comment by verigle** [comment]
您能提供一下训练好的模型呢？
如果你愿意的话可以发送到我邮箱 verigle@foxmail.com

**Comment by supernotman** [comment]
> 在detect.py 文件中，有padded image 这一环节，你是否考虑过对于大小不是640×640的图片，在padding和resize之后输入的模型中，得到的人脸框的位置和关键点的位置与原图之间会有偏移？这个偏移是否应该在显示的时候矫正一下呢？

是这样的，之前的做法是先padding,然后直接拿padding和resize的图像做检测，所以不存在便宜。
但是最近代码更新过了，已经支持不做padding直接用任意尺寸来做检测，upadate代码一下再试一下。

**Comment by Joll123** [comment]
@supernotman 您能发我一份训练好的模型吗？我这条件不足。谢谢1205665754@qq.com

**Comment by supernotman** [comment]
> @supernotman 您能发我一份训练好的模型吗？我这条件不足。谢谢[1205665754@qq.com](mailto:1205665754@qq.com)

预训练模型更新在readme里更新了链接，可以自行下载。
