### ISSUE TITLE
when do inference, load model is wrong?

### ISSUE THREAD

**Issue by foocker** [supernotman/RetinaFace_Pytorch#16]
RuntimeError: Error(s) in loading state_dict for RetinaFace
Missing key(s) in state_dict: "body.conv1.weight", "body.bn1.weight", "body.bn1.bias",....
Unexpected key(s) in state_dict: "module.body.conv1.weight", "module.body.bn1.weight",...

**Comment by aman071** [comment]
i'm facing the same issue. do you have a solution?
