### ISSUE TITLE
Allow for dynamic input sizes / anchor sizes

### ISSUE THREAD

**Issue by xsacha** [supernotman/RetinaFace_Pytorch#5]
Currently when tracing the model, the following two warnings apply:

> /d/dev/RetinaFace_Pytorch/anchors.py:27: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   image_shape = np.array(image_shape)
> /d/dev/RetinaFace_Pytorch/anchors.py:40: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
>   return torch.from_numpy(all_anchors.astype(np.float32)).cuda()

The model is then using a hardcoded 640x640 input size and anchors whereas the input size should be dynamic.

**Comment by supernotman** [comment]
> Currently when tracing the model, the following two warnings apply:
> 
> > /d/dev/RetinaFace_Pytorch/anchors.py:27: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> > image_shape = np.array(image_shape)
> > /d/dev/RetinaFace_Pytorch/anchors.py:40: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
> > return torch.from_numpy(all_anchors.astype(np.float32)).cuda()
> 
> The model is then using a hardcoded 640x640 input size and anchors whereas the input size should be dynamic.

Not really ,actually the anchors varies when input size are different。
 as code in torchvison_model.py forward:
`anchors = self.anchors(img_batch)`
anchors will change with different batch of img.
When training it will be 640,and for detect,other sizes you can use instead.

**Comment by xsacha** [comment]
When tracing, however, you have to specify a size and it will currently be hardcoded to that version because the anchors are part of the model.

If it was split as a post process on the model result, it wouldn't matter about tracing it. Otherwise the numpy stuff gets treated as constants when tracing.
