### ISSUE TITLE
element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by yuemengyuan** [supernotman/RetinaFace_Pytorch#6]
Thank you for your open source, but I encountered the following problem when 104 epoch in training.can you help me? thanks

Traceback (most recent call last):
  File "train.py", line 156, in <module>
    main()
  File "train.py", line 111, in main
    loss.backward()
  File "/home/boyun/.conda/envs/retinaface/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/boyun/.conda/envs/retinaface/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by supernotman** [comment]
> Thank you for your open source, but I encountered the following problem when 104 epoch in training.can you help me? thanks
> 
> Traceback (most recent call last):
> File "train.py", line 156, in
> main()
> File "train.py", line 111, in main
> loss.backward()
> File "/home/boyun/.conda/envs/retinaface/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
> torch.autograd.backward(self, gradient, retain_graph, create_graph)
> File "/home/boyun/.conda/envs/retinaface/lib/python3.6/site-packages/torch/autograd/**init**.py", line 93, in backward
> allow_unreachable=True) # allow_unreachable flag
> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

Can you tell the version of pytorch you are using?

**Comment by yuemengyuan** [comment]
@supernotman 
certifi==2016.2.28　（2019.6.16）
cpools==0.0.0　（installation failed）
cycler==0.10.0
decorator==4.4.0
imageio==2.5.0
kiwisolver==1.1.0
matplotlib==3.1.1
networkx==2.3
numpy==1.16.4　（1.17.0）
opencv-python==4.1.0.25
Pillow==6.1.0
protobuf==3.9.0
pyparsing==2.4.1　（2.4.2）
python-dateutil==2.8.0
PyWavelets==1.0.3
scikit-image==0.15.0
scipy==1.3.0
six==1.12.0
some-package==0.1
tensorboardX==1.8
terminaltables==3.1.0
torch==1.1.0
torchvision==0.3.0
tqdm==4.32.1

**Comment by supernotman** [comment]
> @supernotman
> certifi==2016.2.28　（2019.6.16）
> cpools==0.0.0　（installation failed）
> cycler==0.10.0
> decorator==4.4.0
> imageio==2.5.0
> kiwisolver==1.1.0
> matplotlib==3.1.1
> networkx==2.3
> numpy==1.16.4　（1.17.0）
> opencv-python==4.1.0.25
> Pillow==6.1.0
> protobuf==3.9.0
> pyparsing==2.4.1　（2.4.2）
> python-dateutil==2.8.0
> PyWavelets==1.0.3
> scikit-image==0.15.0
> scipy==1.3.0
> six==1.12.0
> some-package==0.1
> tensorboardX==1.8
> terminaltables==3.1.0
> torch==1.1.0
> torchvision==0.3.0
> tqdm==4.32.1
It seems that the loss does not requires grad.You can try to print your loss checking if  loss.requires_grad is True.

**Comment by yuemengyuan** [comment]
@supernotman 作者您好，我分别打印了三个loss显示都为requires_grad is True．重新训练时在第二个epochs又出现了这个问题，并且我注意到你说

＂I find that when i use random flip Augmentation, Some noises in landmark loss.But i checked the groundtruth and found no wrong label.＂

请问如果训练数据存在NaNs是不是会导致梯度无法下降呢？但很奇怪为什么前几个epochs没问题，还有就是您训练时有没有出现过类似问题？

**Comment by supernotman** [comment]
> @supernotman 作者您好，我分别打印了三个loss显示都为requires_grad is True．重新训练时在第二个epochs又出现了这个问题，并且我注意到你说
> 
> ＂I find that when i use random flip Augmentation, Some noises in landmark loss.But i checked the groundtruth and found no wrong label.＂
> 
> 请问如果训练数据存在NaNs是不是会导致梯度无法下降呢？但很奇怪为什么前几个epochs没问题，还有就是您训练时有没有出现过类似问题？

如果是某一个epoch开始是这个样子，那我觉得有可能是数据的问题，你可以尝试关闭filp，在train.py里面，大概line53左右的位置，去掉RandomFlip()就好了再试一下

**Comment by yuemengyuan** [comment]
> > @supernotman 作者您好，我分别打印了三个loss显示都为requires_grad is True．重新训练时在第二个epochs又出现了这个问题，并且我注意到你说
> > ＂I find that when i use random flip Augmentation, Some noises in landmark loss.But i checked the groundtruth and found no wrong label.＂
> > 请问如果训练数据存在NaNs是不是会导致梯度无法下降呢？但很奇怪为什么前几个epochs没问题，还有就是您训练时有没有出现过类似问题？
> 
> 如果是某一个epoch开始是这个样子，那我觉得有可能是数据的问题，你可以尝试关闭filp，在train.py里面，大概line53左右的位置，去掉RandomFlip()就好了再试一下

您好，train,py默认的是没有用RandomFlip的，应该不是这里的问题
然后我排查发现在losses.py里81-83,157,191,223行里添加torch.tensor(0)时没有requires_grad = True．
并且只torch.tensor(0,requires_grad=True).float().cuda()时也会报错为：Only Tensors of floating point dtype can require gradients
最后我改为torch.tensor(1e-6,requires_grad=True).float().cuda()，目前训练还没有报错，不知道是不是这里的原因，麻烦您可以分析一下吗？非常感谢

**Comment by supernotman** [comment]
> > > @supernotman 作者您好，我分别打印了三个loss显示都为requires_grad is True．重新训练时在第二个epochs又出现了这个问题，并且我注意到你说
> > > ＂I find that when i use random flip Augmentation, Some noises in landmark loss.But i checked the groundtruth and found no wrong label.＂
> > > 请问如果训练数据存在NaNs是不是会导致梯度无法下降呢？但很奇怪为什么前几个epochs没问题，还有就是您训练时有没有出现过类似问题？
> > 
> > 
> > 如果是某一个epoch开始是这个样子，那我觉得有可能是数据的问题，你可以尝试关闭filp，在train.py里面，大概line53左右的位置，去掉RandomFlip()就好了再试一下
> 
> 您好，train,py默认的是没有用RandomFlip的，应该不是这里的问题
> 然后我排查发现在losses.py里81-83,157,191,223行里添加torch.tensor(0)时没有requires_grad = True．
> 并且只torch.tensor(0,requires_grad=True).float().cuda()时也会报错为：Only Tensors of floating point dtype can require gradients
> 最后我改为torch.tensor(1e-6,requires_grad=True).float().cuda()，目前训练还没有报错，不知道是不是这里的原因，麻烦您可以分析一下吗？非常感谢

感谢反馈，我想这个问题首先是因为可能你的标注信息里面有某张图片的标注信息缺失导致的这个问题，但这其实应该也是我代码中的一个bug,当bbox_annotation.shape[0] == 0的时候将返回0的tensor,即loss为0：torch.tensor(0)。
我想我没遇到这个问题可能是因为我没有出现bbox_annotation.shape[0] == 0的情况。
至于你的修改是对的，只需要将返回的tensor(0)的requires_grad=True就好了。但是实现方式上可能有错误，如果按照你现在的实现：
torch.tensor(1e-6,requires_grad=True).float().cuda()
将会返回一个非常小的loss，这个loss虽然非常小，但是可能也会对结果产生一定的影响。
你可以这样修改：
torch.tensor(0.,requires_grad=True).float().cuda()
你那样直接改会出错是因为只有float类型的tensor才能计算grad。
不过总的来说这是我代码中的bug，感谢指正，我会尽快修改的。

**Comment by yuemengyuan** [comment]
作者您好，我注意到您代码中用的是torchvision_model.py创建的retinaface网络，然后不论train.py的depth设为多少，只能创建resnet50，如果我想换成resnet18或者34应该怎么做呢？
是不是只需要打开train.py中61－73行的注释即可？还需要改其他的地方吗？
非常感谢

**Comment by supernotman** [comment]
> 作者您好，我注意到您代码中用的是torchvision_model.py创建的retinaface网络，然后不论train.py的depth设为多少，只能创建resnet50，如果我想换成resnet18或者34应该怎么做呢？
> 是不是只需要打开train.py中61－73行的注释即可？还需要改其他的地方吗？
> 非常感谢
是这样子的，你可以尝试使用比resnet50更深的resnet101和resnet152，在创建retinaface的时候改成：
retinaface = torchvision_model.create_retinaface(return_layers,backbone_name='resnet101')
这样子就好了。
由于resnet34和resnet50的网络结构不一样，如果你想用resnet34，还需要修改torchvision_model.py中的大概in_channels_stage2=256为64
但是我只训练过resnet50其他都不知道效果怎么样
以及 train.py中的61~73行用的不是torchvison实现的model，整个网络结构有些区别，修改后我还没试过 ，不建议修改61~73

**Comment by yuemengyuan** [comment]
@supernotman 非常感谢您的帮助，我刚刚初学有些地方不太明白，想请教您一下．
在anchors.py的shift函数中，shift_x = (np.arange(0, shape[1]) + 0.5) * stride
我的理解是把特征图例如80*80的每个像素点映射回原图640*640中，但不明白为什么要加0.5呢？
如果不加0.5，第一个anchor的中心会从(0,0)开始，而加了以后会以(4,4)为中心点开始，请问这是出于什么考虑从(4,4)开始呢，非常感谢~

**Comment by supernotman** [comment]
> @supernotman 非常感谢您的帮助，我刚刚初学有些地方不太明白，想请教您一下．
> 在anchors.py的shift函数中，shift_x = (np.arange(0, shape[1]) + 0.5) * stride
> 我的理解是把特征图例如80_80的每个像素点映射回原图640_640中，但不明白为什么要加0.5呢？
> 如果不加0.5，第一个anchor的中心会从(0,0)开始，而加了以后会以(4,4)为中心点开始，请问这是出于什么考虑从(4,4)开始呢，非常感谢~

你可以这么理解，映射应该是把anchor的中心映射回原图，举个例子，80*80的feature上（0,0）的点，映射回原图其实代表的是8*8大小的这么一个区域 那在这个区域里面 他的中心并不是（0,0），而是（4,4）,所以加了0.5的shift偏移

**Comment by yuemengyuan** [comment]
> > @supernotman 非常感谢您的帮助，我刚刚初学有些地方不太明白，想请教您一下．
> > 在anchors.py的shift函数中，shift_x = (np.arange(0, shape[1]) + 0.5) * stride
> > 我的理解是把特征图例如80_80的每个像素点映射回原图640_640中，但不明白为什么要加0.5呢？
> > 如果不加0.5，第一个anchor的中心会从(0,0)开始，而加了以后会以(4,4)为中心点开始，请问这是出于什么考虑从(4,4)开始呢，非常感谢~
> 
> 你可以这么理解，映射应该是把anchor的中心映射回原图，举个例子，80×80的feature上（0,0）的点，映射回原图其实代表的是8×8大小的这么一个区域 那在这个区域里面 他的中心并不是（0,0），而是（4,4）,所以加了0.5的shift偏移

明白了,非常感谢^.^
