### ISSUE TITLE
FPS of the model and small face

### ISSUE THREAD

**Issue by luyao777** [supernotman/RetinaFace_Pytorch#7]
Thanks for your work!
Is there any speed test(FPS) of your model? thx!

**Comment by luyao777** [comment]
And small face is difficult to detect, such as 0_Parade_marchingband_1_188 and 0_Parade_marchingband_1_465.

**Comment by supernotman** [comment]
> And small face is difficult to detect, such as 0_Parade_marchingband_1_188 and 0_Parade_marchingband_1_465.

FPS has not been tested.
And for small faces,change the input size in detect.py

> And small face is difficult to detect, such as 0_Parade_marchingband_1_188 and 0_Parade_marchingband_1_465.

Speed has not been tested yet.Maybe in the future.
And for small faces, you can change  size of input from default 640 to a larger scale.
Simply change detect.py, line 77:
`resized_img = resize(padded_img.float(),(640,640))`

**Comment by clancylian** [comment]
> Thanks for your work!
> Is there any speed test(FPS) of your model? thx!

hi,
you will see speed test in my github, i have converted the model to caffe and then to tensorrt int8 model, you can test it! 
[https://github.com/clancylian/retinaface](https://github.com/clancylian/retinaface)

**Comment by luyao777** [comment]
Thx, I tested the FPS, almost 26 FPS in widerface val for (640,640).
